### ISSUE TITLE
Does the opened project require ddev setup?

### ISSUE THREAD

**Issue by theodorosploumis** [drud/ddev-gitpod-launcher#11]
I was wandering if the project to be opened need to already have a ddev integration. If so we need to declare it on the README.

**Comment by rfay** [comment]
Thanks for giving it a try. No, the whole idea is it does not already have to have a .ddev. directory already.  The code for that is probably settling down in https://github.com/drud/ddev-gitpod-launcher/pull/4 but I think it should already work. It does a `ddev config --auto`

**Comment by rfay** [comment]
https://github.com/rfay/d9novendor is a good example to look at - nothing but a composer.json/lock, no previous ddev. Give it a try!

Thanks so much for your engagement and contribution here!
