### ISSUE TITLE
update DDEV to current version

### ISSUE THREAD

**Issue by tyler36** [drud/ddev-gitpod-launcher#22]
When I start a workspace, I get the following warning:

```shell
Upgraded DDEV v1.19.3 is available!
Please visit https://github.com/drud/ddev/releases/tag/v1.19.3 to get the upgrade.
For upgrade help see https://ddev.readthedocs.io/en/stable/#installation
```

It appears to be using an older version of DDEV

```shell
gitpod /workspace/ddev-gitpod-launcher (main) $ ddev -v
ddev version v1.19.2
```

I think version `1.19.4` might be out before the end of the month so it would be ideal if this packaged used the "latest" version.

**Comment by rfay** [comment]
Thanks - This is interesting because I did upgrade the image after a recent PR, and long after v1.19.3. 

So something's funky about gitpod, and we're going to have to ask them about it.  The current version of drud/ddev-gitpod-base:latest is the right one. 

```
$ docker run -it --rm drud/ddev-gitpod-base /usr/local/bin/ddev --version
ddev version v1.19.3
```

/cc @shaal

**Comment by rfay** [comment]
Actually, this isn't fixed. Apparently you have to hit the imagebuild separately for every repo you might ever want to open, which of course is impossible. We may have to do the imagebuild as part of the launch, which will slow it down.

**Comment by rfay** [comment]
Alternately, I think just not using "latest" and instead using a named tag is probably the key thing to do.

**Comment by rfay** [comment]
I think this is fixed for now @tyler36 , please confirm. But for the future:

1. New ddev releases need to have a new push of the drud/ddev-gitpod-base using https://github.com/drud/ddev/blob/master/.gitpod/images/push.sh with a new tag
2. Then both ddev's .gitpod.yml and this .gitpod.yml need to be updated with the new tag.

I think this will resolve at least most of this class of problem, but I don't actually completely understand gitpod's caching strategy. It may be caching specific project builds, not just the base image.

**Comment by tyler36** [comment]
Confirmed. Checked a ["random" project](https://github.com/mandrasch/ddev-addon-simple-vite) with ddev-gidpod launcher. 

```shell
gitpod /workspace/ddev-gitpod-launcher (main) $ ddev --version
ddev version v1.19.3
```

I note that `1.19.5` is out now though. 🤷

**Comment by rfay** [comment]
Good reminder! I'll update those.

**Comment by rfay** [comment]
* https://github.com/drud/ddev/issues/4017

**Comment by rfay** [comment]
Image bumped in https://github.com/drud/ddev-gitpod-launcher/commit/e4c99ec961f732becf91aaba89108d954d4bd18c
